chore: add steam, gamescope and shadowblip rpms

diff --git a/build/ghcurl b/build/ghcurl
--- a/build/ghcurl
+++ b/build/ghcurl
@@ -4,10 +4,10 @@ set -euo pipefail
 # Check for GITHUB_TOKEN in /run/secrets/GITHUB_TOKEN (Podman secret mount)
 if [[ -f /run/secrets/GITHUB_TOKEN ]]; then
   GITHUB_TOKEN=$(< /run/secrets/GITHUB_TOKEN)
-  echo "Using GITHUB_TOKEN from /run/secrets/GITHUB_TOKEN for authentication." >&2
+  #echo "Using GITHUB_TOKEN from /run/secrets/GITHUB_TOKEN for authentication." >&2
   AUTH_HEADER="Authorization: Bearer $GITHUB_TOKEN"
 else
-  echo "GITHUB_TOKEN secret not found. Using unauthenticated requests." >&2
+  #echo "GITHUB_TOKEN secret not found. Using unauthenticated requests." >&2
   AUTH_HEADER=""
 fi
 
